# -*- coding: utf-8 -*-
"""monishv.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gT4MsTFk65M5KOas7kYrnNEksdEMe2Kl
"""

import requests 
import sys
from datetime import datetime

api_key = '47e41b0b50907b1a18d4400ed5f00e82'
location = input("Enter the city name:")

complete_api_link = "http://api.openweathermap.org/data/2.5/weather?q="+location+"&appid="+api_key
api_link = requests.get(complete_api_link)
api_data = api_link.json()

temp_city = ((api_data['main']['temp']) - 273.15)
weather_desc = api_data['weather'][0]['description']
hmdt = api_data['main']['humidity']
wind_spd = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print("------------------------------------------------")
print("Weather stats for - {} || {}".format(location.upper(), date_time))
print("------------------------------------------------") 

print("Current temparature is:{: .2f} deg C".format(temp_city))
print("Current weather desc :",weather_desc)
print("Current Humidity     :",hmdt, '%')
print("Current wind speed   :",wind_spd,'kmph')
with open('weatherdata.txt','wb') as f: 
  f.write(api_link.content)